### ISSUE TITLE
Compat.LinearAlgebra for v0.6

### ISSUE THREAD

**Issue by cortner** [JuliaAlgebra/StaticPolynomials.jl#11]
In `src/StaticPolynomials.jl` the line
```
if VERSION <= v"0.6.2"
```
should be replaced with 
```
if VERSION < v"0.7"
```

(I have v0.6.3-pre running one machine)

**Comment by saschatimme** [comment]
I changed it on master to  `VERSION <= v"0.6.3"`.  Do you need a new release or is it fine if we wait a little bit if something else comes up?

FIY: `VERSION < v"0.7"` doesn't work because every nightly currently satisfies this.

**Comment by cortner** [comment]
good point. What if you ask <= 0.6?

**Comment by cortner** [comment]
or <= 0.6.x? . there must be some way

For me this is fine, it just seemed strange. And once 0.7 is out there will probably be 1-2 more 0.6.x updat4es.

**Comment by saschatimme** [comment]
Yeah it's a little bit strange
```julia
julia> v"0.6.3" ≤ v"0.6"
false
julia> v"0.6.3" ≤ v"0.6.x"
ERROR: LoadError: ArgumentError: invalid version string: 0.6.x
Stacktrace:
 [1] VersionNumber(::String) at ./version.jl:95
 [2] @v_str(::LineNumberNode, ::Module, ::Any) at ./version.jl:108
in expression starting at REPL[8]:1
```

So I just bumped it to `VERSION < v"0.6.9"`. There is probably a better way, but this should be enough.

**Comment by cortner** [comment]
Perfect - thank you
